### ISSUE TITLE
Map to array

### ISSUE THREAD

**Issue by rafakato** [russmatney/super-object-mapper#7]
Hello,

Is there a way to map a object like this:

``` json
[{
    "title": "Product Title",
    "price": 199
}, {
    "title": "Product 2 Title",
    "price": 399
}]
```

to this:

``` json
[{
    "name": "Product Title",
    "price": [{
        "list": 199,
        "value": 199
    }]
}, {
    "name": "Product 2 Title",
    "price": [{
        "list": 399,
        "value": 399
    }]
}]
```

I thought of a map like this:

``` js
var map = {
    "products": {
        {
            "title": "name",
            "price": "price[].list",
            "price": "price[].value"
        }
    }
}
```

Thanks

**Comment by russmatney** [comment]
That's a great idea and a unique use-case, i'd love to see a PR for the feature, and the tests at least shouldn't be hard to write. 

You might be able to do this directly with [wankdanker's object-mapper](https://github.com/wankdanker/node-object-mapper) that this module is built on top of. I'd look into writing your own transform function for the price field.

**Comment by rafakato** [comment]
I thought about doing a transform for it, but I'll use your package in a project that I need the map be configurable by the user, so it needs to be simple.

I'll check the code and try to work doing like I said.

**Comment by rafakato** [comment]
Hi

I've just made the modifications in the wankdanker's object-mapper project, can you update to version 2.0.0?

Thanks

**Comment by russmatney** [comment]
Yeah – I can get to it this this weekend. Thanks for putting the time in! I'll check it out and update when I get a minute.

**Comment by russmatney** [comment]
@rafakato sorry for such a delay! Updated and published just now.
